### ISSUE TITLE
Support https base URLs in validation and registration system

### ISSUE THREAD

**Issue by zimeon** [zimeon/www.openarchives.org#2]
The current code does not support https, the replacement validation code https://github.com/zimeon/oaipmh-validator does support https but this still needs to be wrapped in put online at www.openarchives.org. Will collect here base URLs where users can't register.

**Comment by zimeon** [comment]
Texas Water Journal https://journals.tdl.org/twj/index.php/twj/oai (contact Kathy Wythe)

**Comment by zimeon** [comment]
Publication Server of the University of Potsdam
http://opus.kobv.de/ubp/oai2/oai2.php
has changed its BaseURL
https://publishup.uni-potsdam.de/opus4-ubp/oai

**Comment by zimeon** [comment]
Texas Digital Library manages a number of DSpace installations, e.g. https://uta-ir.tdl.org/uta-oai/request?verb=Identify (contact Ryan Steans)

**Comment by zimeon** [comment]
TU Berlin repo: <https://depositonce.tu-berlin.de/oai/request> supports only https (contact Michaela Voigt)

**Comment by zimeon** [comment]
ZIB.de repo: https://opus4.kobv.de/opus4-th-wildau/oai is https since 2015 (contact Signe Weihe)

**Comment by zimeon** [comment]
In #7 @MakabaM would like to register base URL somewhere under  https://ujcontent.uj.ac.za/

**Comment by peterdietz** [comment]
HTTPS issue when validating/registering: https://darchive.mblwhoilibrary.org/oai/request

**Comment by cmmills** [comment]
HTTP issue when validating https://rucore.libraries.rutgers.edu/api/oai-pmh/

**Comment by cyberthecaire** [comment]
HTTP issue when validating https://eduq.info

**Comment by kajozi** [comment]
HTTP issue when validating https://kola.opus.hbz-nrw.de/oai or https://kola.opus.hbz-nrw.de/oai?verb=Identify

**Comment by QUHAS** [comment]
journal.uinjkt.ac.id/index.php/journal-of-quran-and-hadith

**Comment by pilasou** [comment]
HTTPS issue when validating https://corpus.ulaval.ca/oai/request

**Comment by zimeon** [comment]
Error - `http://dspace.cusat.ac.in' is not an HTTP URL and therefore cannot be validated.

**Comment by radzuwan** [comment]
https://journal.unisza.edu.my/jonus/index.php/jonus/oai

**Comment by michaelsse** [comment]
HTTPS issue when validating/registering: https://repository.westernsem.edu/oai/request

**Comment by zimeon** [comment]
Request from <https://e-pub.uni-weimar.de/opus4/oai> "Online-Publikations-System der Bauhaus-Universität Weimar"

**Comment by sfbetz** [comment]
HTTPS error when validating: https://journals.library.ualberta.ca/hssa/index.php/hssa/oai

**Comment by cepek** [comment]
HTTPS error when validating:  https://ojs.cvut.cz/ojs/index.php/gi/oai

**Comment by LuqmanH** [comment]
HTTPS errors when validating:
https://ojs.aut.ac.nz/applied-finance-letters/oai
https://ojs.aut.ac.nz/pacific-journalism-review/oai

**Comment by kcondon** [comment]
Please register this URL:
https://dataverse.harvard.edu/oai

**Comment by rlucas1978** [comment]
@kcondon did you receive a response from your post?

**Comment by kcondon** [comment]
@rlucas1978 No, I have not.

**Comment by zimeon** [comment]
@kcondon @rlucas1978 - this is a laundry list of URIs that cannot currently be registered, waiting for action when they can

**Comment by zimeon** [comment]
Have put online support for HTTPS (as part of #8) and gone through the list above:

  * https://journals.tdl.org/twj/index.php/twj/oai -- registered 
  * https://publishup.uni-potsdam.de/opus4-ubp/oai -- have registered https://publishup.uni-potsdam.de/oai which is the URI in Identify
  * https://uta-ir.tdl.org/uta-oai/request -- registered
  * https://depositonce.tu-berlin.de/oai/request -- registered
  * https://opus4.kobv.de/opus4-th-wildau/oai -- registered
  * https://ujcontent.uj.ac.za/ -- not an OAI-PMH base URL
  * https://darchive.mblwhoilibrary.org/oai/request -- will need to register after changing base URL in Identify from `http://darchive.mblwhoilibrary.org/oai/request`
  * https://rucore.libraries.rutgers.edu/api/oai-pmh/ -- fails tests
  * https://eduq.info/oai/request -- registered
  * https://kola.opus.hbz-nrw.de/oai -- fails (Bad namespace-identifier)
  * https://journal.uinjkt.ac.id/index.php/journal-of-quran-and-hadith -- fail (HTTP 500)
  * https://corpus.ulaval.ca/oai/request -- registered
  * http://dspace.cusat.ac.in -- base URL seems to be http://dspace.cusat.ac.in/oai/request -- registered
  * https://journal.unisza.edu.my/jonus/index.php/jonus/oai -- registered
  * https://repository.westernsem.edu/oai/request -- will need to regsister after updating base URL in Identify from `http://repository.westernsem.edu/oai/request`
  * https://e-pub.uni-weimar.de/opus4/oai -- registered
  * https://journals.library.ualberta.ca/hssa/index.php/hssa/oai -- fails (Bad namespace-identifier)
  * https://ojs.cvut.cz/ojs/index.php/gi/oai -- registered
  * https://ojs.aut.ac.nz/applied-finance-letters/oai -- registered
  * https://ojs.aut.ac.nz/pacific-journalism-review/oai -- registered
  * https://dataverse.harvard.edu/oai -- registered
