### ISSUE TITLE
New Base URL

### ISSUE THREAD

**Issue by MakabaM** [zimeon/www.openarchives.org#5]
Dear Simeon

I want to register a new URL base line for our new repository: https://ujcontent.uj.ac.za/, we have moved from https://ujdigispace.uj.ac.za/. The validation process does not like our new base line it seems i am struggling to get started.
Please help.

Regards
Makaba Macanda

**Comment by zimeon** [comment]
See #2 -- the validator does no yet support https

**Comment by MakabaM** [comment]
Hi Simeon, are you guys going to support this? Or how do you advise us to do?

Regards

Makaba

**Comment by zimeon** [comment]
I do hope to support https but cannot commit to a timeframe
